// src/app/hero/hero.component.ts
import { Component } from "@angular/core";
import {
  bootstrapEnvelopeFill,
  bootstrapGithub,
  bootstrapLinkedin,
} from "@ng-icons/bootstrap-icons";
import { NgIcon, provideIcons } from "@ng-icons/core";

@Component({
  selector: "app-hero",
  imports: [NgIcon],
  viewProviders: [
    provideIcons({ bootstrapLinkedin, bootstrapGithub, bootstrapEnvelopeFill }),
  ],
  templateUrl: "./hero.component.html",
  styleUrl: "./hero.component.css",
})
export class HeroComponent {
  scrollToSection(sectionId: string): void {
    const element = document.getElementById(sectionId);
    if (element) {
      element.scrollIntoView({ behavior: "smooth" });
    }
  }
}

<section
  id="hero"
  class="min-h-screen flex items-center justify-center bg-gradient-to-br from-[#000050] via-purple-900 to-[#000050]"
>
  <div class="container mx-auto px-6 text-center">
    <div class="animate-fade-in">
      <h1 class="text-5xl md:text-7xl font-bold text-white mb-6 leading-tight">
        Tech Stack
        <span
          class="bg-gradient-to-r from-purple-400 to-pink-400 bg-clip-text text-transparent"
        >
          Tamer
        </span>
      </h1>
      <p
        class="text-xl md:text-2xl text-gray-300 mb-8 max-w-3xl mx-auto leading-relaxed"
      >
        From frontend to backend and everything between. Building modern web
        applications and robust REST APIs with cutting-edge technologies.
        Passionate about learning new languages and creating scalable solutions.
      </p>
      <div
        class="flex flex-col md:flex-row justify-center gap-14 pt-5 text-white"
      >
        <div>
          <button
            class="cursor-pointer bg-gradient-to-r text-2xl from-purple-500 to-pink-500 hover:from-purple-600 hover:to-pink-600 text-white px-8 py-3 rounded-full font-semibold transition-all duration-300 transform hover:scale-105"
            (click)="scrollToSection('projects')"
          >
            View My Work
          </button>
        </div>
        <div class="flex text-5xl space-x-5 items-center justify-center">
          <ng-icon name="bootstrapLinkedin" />
          <ng-icon name="bootstrapGithub" />
          <ng-icon name="bootstrapEnvelopeFill" />
        </div>
      </div>
    </div>
  </div>
</section>

// project/src/components/Hero.tsx
import React from 'react';
import { ArrowDown, Github, Linkedin, Mail } from 'lucide-react';

const Hero = () => {
  const scrollToProjects = () => {
    const element = document.querySelector('#projects');
    if (element) {
      element.scrollIntoView({ behavior: 'smooth' });
    }
  };

  return (
    <section id="home" className="min-h-screen flex items-center justify-center relative overflow-hidden">
      {/* Background gradient */}
      <div className="absolute inset-0 bg-gradient-to-br from-slate-900 via-blue-900 to-slate-800"></div>
      
      {/* Animated background elements */}
      <div className="absolute inset-0 opacity-20">
        <div className="absolute top-1/4 left-1/4 w-72 h-72 bg-blue-500 rounded-full mix-blend-multiply filter blur-xl animate-pulse"></div>
        <div className="absolute top-1/3 right-1/4 w-72 h-72 bg-purple-500 rounded-full mix-blend-multiply filter blur-xl animate-pulse animation-delay-2000"></div>
        <div className="absolute bottom-1/4 left-1/3 w-72 h-72 bg-pink-500 rounded-full mix-blend-multiply filter blur-xl animate-pulse animation-delay-4000"></div>
      </div>

      <div className="relative z-10 text-center text-white px-4 sm:px-6 lg:px-8 max-w-4xl mx-auto">
        <div className="animate-fade-in-up">
          <h1 className="text-5xl sm:text-6xl lg:text-7xl font-bold mb-6 leading-tight">
            Full Stack
            <span className="block text-transparent bg-clip-text bg-gradient-to-r from-blue-400 to-emerald-400">
              Developer
            </span>
          </h1>
          
          <p className="text-xl sm:text-2xl text-slate-300 mb-8 leading-relaxed max-w-3xl mx-auto">
            Crafting exceptional web experiences and robust REST APIs with modern technologies. 
            Passionate about clean code, scalable architecture, and innovative solutions.
          </p>

          <div className="flex flex-col sm:flex-row items-center justify-center gap-6 mb-12">
            <button 
              onClick={scrollToProjects}
              className="bg-blue-600 hover:bg-blue-700 text-white font-semibold py-4 px-8 rounded-full transition-all duration-300 transform hover:scale-105 shadow-lg hover:shadow-xl"
            >
              View My Work
            </button>
            
            <div className="flex items-center space-x-4">
              <a href="#" className="p-3 bg-white/10 backdrop-blur-sm rounded-full hover:bg-white/20 transition-all duration-300 transform hover:scale-110">
                <Github className="h-6 w-6" />
              </a>
              <a href="#" className="p-3 bg-white/10 backdrop-blur-sm rounded-full hover:bg-white/20 transition-all duration-300 transform hover:scale-110">
                <Linkedin className="h-6 w-6" />
              </a>
              <a href="#" className="p-3 bg-white/10 backdrop-blur-sm rounded-full hover:bg-white/20 transition-all duration-300 transform hover:scale-110">
                <Mail className="h-6 w-6" />
              </a>
            </div>
          </div>
        </div>
      </div>

      {/* Scroll indicator */}
      <div className="absolute bottom-8 left-1/2 transform -translate-x-1/2 animate-bounce">
        <ArrowDown className="h-6 w-6 text-white/70" />
      </div>
    </section>
  );
};

export default Hero;
